site_name: Chet Sheets
nav:
  - Home: index.md
  - About: about.md
theme:
  name: material
  logo: assets/images/logo.png
  features:
    - navigation.footer
    - navigation.sections
    - navigation.indexes
    - navigation.top
copyright: "© 2023 Martin Vach"
