# Basics
site_name: Chet Sheets
nav:
  - Home: index.md
  - Cheat Sheets: cheat-sheets.md
  - Tags: tags.md
  - About: about.md
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.png
  search:
    provider: "internal"
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.top
copyright: "© 2023 Martin Vach"
extra_css:
  - "styles/styles.css"
# blog implementation
site_url: http://127.0.0.1:8000/
plugins:
  - blogging:
      features:
        tags: {}
      dirs: # The directories to be included
        - blog
      categories:
        - name: cheat-sheets
          dirs:
            - cheat-sheets
      template: overrides/my-blog.html
      full_content: false
      time_format: "%Y-%m-%d"
      meta_time_format: "%Y-%m-%d"
      locale: en
