# Basics
site_name: Chet Sheets
_nav:
  - Home: index.md
  - Pages:
      - pages/index.md
  - Tags: pages/tags.md
  - About: pages/about.md
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.png
  search:
    provider: "internal"
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - navigation.tracking
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
copyright: "© 2023 Martin Vach"
extra_css:
  - "styles/styles.css"
# blog implementation
site_url: https://vades.github.io/cheatsheets/ #http://127.0.0.1:8000/
watch:
  - "overrides"
plugins:
  - search:
      min_search_length: 2
  - extra-sass
  - awesome-pages
  - blogging:
      features:
        tags: {}
      dirs: # The directories to be included
        - blog
      categories:
        - name: cheat-sheets
          dirs:
            - cheat-sheets
      template: overrides/custom-blog.html
      full_content: false
      time_format: "%Y-%m-%d"
      meta_time_format: "%Y-%m-%d"
      locale: en
